---
abstract: 'interpret OBEX protocol response packets'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OBEX-Response
provides:
  Net::OBEX::Response:
    file: lib/Net/OBEX/Response.pm
    version: 0.004
  Net::OBEX::Response::Connect:
    file: lib/Net/OBEX/Response/Connect.pm
    version: 0.004
  Net::OBEX::Response::Generic:
    file: lib/Net/OBEX/Response/Generic.pm
    version: 0.004
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Net::OBEX::Packet::Headers: 0.002
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.004
